--[[
	TaskService - the server-authoritative task pipeline: self-assignment
	(RequestTask), Manager assignment to another player (AssignTask), and
	decision + completion (CompleteTask) - plus, as a side effect of
	completion, promotion checking (Phase 3).

	Phase 3 scope: one task, a real decision (2-3 choices), server-
	controlled outcome resolution, Associate -> Manager promotion, and
	the one new Manager capability (assigning the existing task to
	another player - NOT a second task system). See
	docs/mvp-definition-v0.1.md's Phase 1-3 briefs and
	docs/technical-architecture-v0.1.md §10-§13.

	SECURITY MODEL (this is the whole point of Phases 1-3):
	The client can only ever send opaque values: taskId/instanceId/
	choiceId to CompleteTask, targetUserId to AssignTask. None is trusted
	as authoritative - all are looked up against server-held state (the
	per-player instance table below, PlayerDataService's session records,
	and the server-only task/choice definitions in
	Shared/Data/TaskDefinitions.lua). The client NEVER sends, and this
	module NEVER reads from the client, a reward amount, a performance
	amount, a reputation amount, a quality score, a completion flag, a
	rank, a promotion-eligibility flag, or anything about organization
	state. `userId` (and, for AssignTask, the assigning Manager's own
	identity) is likewise never taken from client input - see
	Bootstrap.server.lua, which passes only the Roblox-engine-verified
	`player.UserId` from a RemoteEvent's server-populated first argument.
	Any randomness in an outcome is resolved with a roll generated by
	THIS module (self._random), never accepted from the client. Whether a
	player is a Manager is read fresh from PlayerDataService on every
	AssignTask call, never cached from or trusted from the client.

	Dependency-injected (playerDataService, taskDefinitions, taskInstance,
	taskOutcome, weightedOutcome, choicePreview, rateLimiter, schema,
	promotionService all passed via config) so this module has zero
	internal `require` calls and can be exercised by the standalone test
	suite against fakes - see technical-architecture-v0.1.md §18.
]]

local TaskService = {}
TaskService.__index = TaskService

-- Bounds how many instances (pending + completed) are retained per
-- player, so a long session's in-memory instance table doesn't grow
-- unboundedly. Pruning only ever removes COMPLETED instances, oldest
-- first, and never a still-pending one. This is a memory-hygiene bound,
-- not a persisted value - task instances are never written to
-- DataStore (see Phase 1 report §11, "persist only the minimum
-- required state").
TaskService.MAX_TRACKED_INSTANCES_PER_PLAYER = 50

-- Convention (see TaskDefinitions.lua): every choice's Outcomes list has
-- Weights summing to exactly 100, so a roll is drawn uniformly from
-- [1, 100].
TaskService.OUTCOME_ROLL_MAX = 100

--[[
	config:
		playerDataService (required) - a Phase 0 PlayerDataService instance
		taskDefinitions (required) - the TaskDefinitions data module
		taskInstance (required) - the TaskInstance logic module
		taskOutcome (required) - the TaskOutcome logic module
		weightedOutcome (required) - the WeightedOutcome logic module (passed
			through to taskOutcome.Resolve; see TaskOutcome.lua)
		choicePreview (required) - the ChoicePreview logic module, used to
			build the client-safe "what are my choices" payload for RequestTask
		rateLimiter (required) - the ActionRateLimiter logic module
		schema (required) - the PlayerData schema module (for RANK constants,
			used by AssignTask's Manager/Associate authorization checks)
		promotionService (required) - a PromotionService instance, checked as
			a side effect of a successful CompleteTask (technical architecture
			§11: promotion is checked event-driven, after each Task completion)
		defaultTaskId (optional) - defaults to taskDefinitions.DEFAULT_TASK_ID
		now (optional) - function() -> number, defaults to os.time. Used
			for persisted-shaped timestamps (instance IssuedAt/CompletedAt,
			mirroring the 1-second-resolution convention the rest of the
			codebase uses for stored timestamps - see PlayerData/
			OrganizationData CreatedAt/LastLogin, SessionLock.ClaimedAt).
		clock (optional) - function() -> number, defaults to os.clock.
			Used ONLY for rate-limit spacing (self._lastActionAt), which
			needs sub-second resolution: two legitimate actions (e.g.
			RequestTask immediately followed by choosing an option) can
			easily land within the same os.time() second, so the rate
			limiter must not share that clock's granularity. In real
			Roblox, os.clock() is a monotonic wall-clock-seconds timer
			(the modern replacement for the deprecated tick()), which is
			exactly what a sub-second cooldown needs.
		random (optional) - function(lo, hi) -> number, defaults to
			math.random. Used both for instance-id nonces and for the
			server-controlled outcome roll (see CompleteTask) - tests
			inject a fixed/controlled function to make specific outcome
			branches deterministic.
		log (optional) - function(message), defaults to a no-op
]]
function TaskService.new(config)
	config = config or {}
	assert(config.playerDataService, "TaskService requires config.playerDataService")
	assert(config.taskDefinitions, "TaskService requires config.taskDefinitions")
	assert(config.taskInstance, "TaskService requires config.taskInstance")
	assert(config.taskOutcome, "TaskService requires config.taskOutcome")
	assert(config.weightedOutcome, "TaskService requires config.weightedOutcome")
	assert(config.choicePreview, "TaskService requires config.choicePreview")
	assert(config.rateLimiter, "TaskService requires config.rateLimiter")
	assert(config.schema, "TaskService requires config.schema")
	assert(config.promotionService, "TaskService requires config.promotionService")

	local self = setmetatable({}, TaskService)
	self._playerDataService = config.playerDataService
	self._taskDefinitions = config.taskDefinitions
	self._taskInstance = config.taskInstance
	self._taskOutcome = config.taskOutcome
	self._weightedOutcome = config.weightedOutcome
	self._choicePreview = config.choicePreview
	self._rateLimiter = config.rateLimiter
	self._schema = config.schema
	self._promotionService = config.promotionService
	self._defaultTaskId = config.defaultTaskId or config.taskDefinitions.DEFAULT_TASK_ID
	self._now = config.now or os.time
	self._clock = config.clock or os.clock
	self._random = config.random or math.random
	self._log = config.log or function() end

	-- userId -> { [instanceId] = TaskInstance }
	self._instances = {}
	-- userId -> timestamp of the last allowed RequestTask/CompleteTask call
	self._lastActionAt = {}

	return self
end

-- Internal: checks AND (on success) records this action's timestamp
-- against the per-player rate limiter, using self._clock (not self._now -
-- see the constructor docs above for why the two are deliberately
-- different clocks).
function TaskService:_checkRateLimit(userId)
	local now = self._clock()
	if not self._rateLimiter.ShouldAllow(self._lastActionAt[userId], now) then
		return false
	end
	self._lastActionAt[userId] = now
	return true
end

function TaskService:_newInstanceId(userId)
	return string.format("ti:%d:%d:%d", userId, self._now(), self._random(1, 1000000000))
end

-- Internal: drops the oldest COMPLETED instances for userId once the
-- tracked count exceeds MAX_TRACKED_INSTANCES_PER_PLAYER. Never prunes a
-- pending (not yet completed) instance.
function TaskService:_pruneInstances(userId)
	local instances = self._instances[userId]
	if not instances then
		return
	end

	local count = 0
	for _ in pairs(instances) do
		count = count + 1
	end
	if count <= TaskService.MAX_TRACKED_INSTANCES_PER_PLAYER then
		return
	end

	-- Collect completed instances, oldest first, and drop from the front
	-- until back under the cap.
	local completed = {}
	for instanceId, instance in pairs(instances) do
		if instance.Completed then
			table.insert(completed, { instanceId = instanceId, completedAt = instance.CompletedAt or 0 })
		end
	end
	table.sort(completed, function(a, b)
		return a.completedAt < b.completedAt
	end)

	local toRemove = count - TaskService.MAX_TRACKED_INSTANCES_PER_PLAYER
	for i = 1, math.min(toRemove, #completed) do
		instances[completed[i].instanceId] = nil
	end
end

--[[
	Internal: creates and registers a new pending task instance for
	`holderUserId` (the player who will complete it), optionally tagged
	with `assignedBy` (a Manager's userId, or nil for a self-request).
	Shared by RequestTask (self-service) and AssignTask (Manager ->
	Associate) so there is exactly one instance-creation/pruning code
	path - "do not create a second task system" per the Phase 3 brief.

	Refuses to create a second instance while one is still pending for
	`holderUserId`, which doubles as both a sensible rule ("one task at a
	time") and a cheap abuse guard against instance-table growth - this
	applies identically whether the holder requested it themselves or a
	Manager assigned it to them (covers "prevent duplicate task
	assignment").

	Returns (true, { InstanceId, TaskId, Name, Prompt, Choices }) on
	success, or (false, errorMessage) on failure.
]]
function TaskService:_assignInstanceTo(holderUserId, assignedBy)
	local instances = self._instances[holderUserId]
	if instances then
		for _, instance in pairs(instances) do
			if not instance.Completed then
				return false, "a task is already in progress"
			end
		end
	else
		instances = {}
		self._instances[holderUserId] = instances
	end

	local definition = self._taskDefinitions.FindById(self._defaultTaskId)
	if not definition then
		-- Defensive: should be unreachable given a correctly configured
		-- TaskDefinitions module, but never assign an instance for an
		-- unknown definition.
		return false, "no task available"
	end

	local now = self._now()
	local instanceId = self:_newInstanceId(holderUserId)
	local instance = self._taskInstance.New(definition.TaskId, instanceId, now, assignedBy)
	instances[instanceId] = instance

	self:_pruneInstances(holderUserId)

	return true, {
		InstanceId = instance.InstanceId,
		TaskId = instance.TaskId,
		Name = definition.Name,
		Prompt = definition.Prompt,
		Choices = self._choicePreview.Build(definition),
	}
end

--[[
	Assigns the single task to `userId`, self-service. Requires the
	player to already have an active PlayerDataService session (i.e. to
	have joined - see Bootstrap.server.lua's PlayerAdded handler).

	Returns (true, { InstanceId, TaskId, Name, Prompt, Choices }) on
	success, or (false, errorMessage) on failure. `Choices` is built by
	ChoicePreview purely from server-held data - see the Phase 2 design
	principle that a player must be able to see what their choices are
	and what they're likely to cost/earn BEFORE deciding. This is a
	read-only preview, not something the server later trusts back from
	the client (see CompleteTask below).
]]
function TaskService:RequestTask(userId)
	assert(type(userId) == "number", "userId must be a number")

	if not self:_checkRateLimit(userId) then
		return false, "rate limited"
	end

	if not self._playerDataService:GetLoadedRecord(userId) then
		return false, "no active session for user"
	end

	return self:_assignInstanceTo(userId, nil)
end

--[[
	The one new Manager capability (Phase 3): assigns the existing task
	to another eligible Associate. `managerUserId`, `targetUserId`: the
	only inputs, both plain userIds resolved against server-held
	PlayerDataService session state - the client's claim about its own
	rank or the target's eligibility is never trusted; both are
	re-checked here from scratch on every call.

	Eligibility, checked in order:
	  - managerUserId must have an active session and be Rank == Manager
	    (never a client-supplied claim - see the module SECURITY MODEL
	    comment). Covers "prevent unauthorized Associate assignment
	    attempts."
	  - targetUserId must not equal managerUserId ("assigning to self").
	  - targetUserId must have an active session (covers "assign to
	    nonexistent/offline" - both look identical from here: no loaded
	    record).
	  - targetUserId must be Rank == Associate (covers "assign to
	    ineligible player" - a Manager cannot assign to another Manager
	    in this minimal scope; responsibility flows downward only).
	  - targetUserId must be in the SAME organization as managerUserId
	    (Organization Systems Spec §6/§11's Department-authority shape,
	    applied to this flat MVP structure: OrgId match stands in for
	    "direct report").
	  - targetUserId must not already have a task in progress (shared
	    with RequestTask via _assignInstanceTo - covers "assign duplicate
	    task").

	Returns (true, { InstanceId, TaskId, Name, Prompt, Choices,
	  TargetUserId, AssignedBy }) on success, or (false, errorMessage).
]]
function TaskService:AssignTask(managerUserId, targetUserId)
	assert(type(managerUserId) == "number", "managerUserId must be a number")

	-- managerUserId is always server-provided (the engine-verified Remote
	-- sender - see the module SECURITY MODEL comment), so it's asserted
	-- like CompleteTask's `userId`. targetUserId, however, IS client-
	-- supplied (the Manager's client picks who to assign to), so it gets
	-- the same graceful malformed-type rejection CompleteTask uses for
	-- its client-supplied taskId/instanceId/choiceId - never a hard
	-- error on bad client input.
	if type(targetUserId) ~= "number" then
		return false, "malformed request"
	end

	if not self:_checkRateLimit(managerUserId) then
		return false, "rate limited"
	end

	local managerRecord = self._playerDataService:GetLoadedRecord(managerUserId)
	if not managerRecord then
		return false, "no active session for user"
	end

	if managerRecord.Rank ~= self._schema.RANK.MANAGER then
		return false, "only a Manager may assign tasks"
	end

	if targetUserId == managerUserId then
		return false, "cannot assign a task to yourself"
	end

	local targetRecord = self._playerDataService:GetLoadedRecord(targetUserId)
	if not targetRecord then
		return false, "target player is not available"
	end

	if targetRecord.Rank ~= self._schema.RANK.ASSOCIATE then
		return false, "target player is not an eligible Associate"
	end

	if targetRecord.OrgId ~= managerRecord.OrgId then
		return false, "target player is not in your organization"
	end

	local ok, resultOrErr = self:_assignInstanceTo(targetUserId, managerUserId)
	if not ok then
		return false, resultOrErr
	end

	resultOrErr.TargetUserId = targetUserId
	resultOrErr.AssignedBy = managerUserId
	return true, resultOrErr
end

--[[
	Submits a decision and completes a previously-assigned task instance
	for `userId`.

	taskId, instanceId, choiceId: the ONLY client-controllable inputs.
	All three are opaque references validated against server-held state -
	see the module-level SECURITY MODEL comment above. None of them is a
	reward, performance, reputation, quality, or outcome value.

	Returns (true, resultTable) on success, where resultTable is
	{ ChoiceId, ResultLabel, QualityScore, MoneyGain, PerformanceGain,
	  ReputationGain, NewPersonalMoney, NewPerformanceRating, NewReputation,
	  Rank, PerformanceThreshold, ReputationThreshold, PromotionEligible,
	  Promotion (present only when a promotion just occurred this call) },
	or (false, errorMessage) on failure (unknown instance, task id
	mismatch, already completed, invalid choice, rate limited, no active
	session, malformed request).
]]
function TaskService:CompleteTask(userId, taskId, instanceId, choiceId)
	assert(type(userId) == "number", "userId must be a number")

	if type(taskId) ~= "string" or type(instanceId) ~= "string" or type(choiceId) ~= "string" then
		return false, "malformed request"
	end

	if not self:_checkRateLimit(userId) then
		return false, "rate limited"
	end

	if not self._playerDataService:GetLoadedRecord(userId) then
		return false, "no active session for user"
	end

	local instances = self._instances[userId]
	local instance = instances and instances[instanceId] or nil

	local canComplete, reason = self._taskInstance.ValidateCompletion(instance, taskId)
	if not canComplete then
		return false, reason
	end

	local definition = self._taskDefinitions.FindById(instance.TaskId)
	if not definition then
		-- Defensive: the instance referenced a task definition that no
		-- longer exists. Should be unreachable (one static definition,
		-- never removed at runtime), but never fabricate a reward for an
		-- unknown definition.
		return false, "task definition no longer exists"
	end

	local choice = self._taskDefinitions.FindChoice(definition, choiceId)
	if not choice then
		return false, "invalid choice"
	end

	local now = self._now()

	-- Server-generated, server-controlled roll - never accepted from the
	-- client. Irrelevant for a single-outcome (Weight=100) choice;
	-- selects among multiple weighted outcomes for a risky choice.
	local roll = self._random(1, TaskService.OUTCOME_ROLL_MAX)
	local reward = self._taskOutcome.Resolve(choice, roll, self._weightedOutcome)

	instances[instanceId] = self._taskInstance.MarkCompleted(instance, now)

	local applyOk, recordOrErr = self._playerDataService:ApplyTaskCompletion(userId, {
		MoneyGain = reward.MoneyGain,
		PerformanceGain = reward.PerformanceGain,
		ReputationGain = reward.ReputationGain,
		HistoryEntry = {
			TaskId = definition.TaskId,
			InstanceId = instanceId,
			ChoiceId = reward.ChoiceId,
			ResultLabel = reward.ResultLabel,
			QualityScore = reward.QualityScore,
			CompletedAt = now,
			MoneyGain = reward.MoneyGain,
			PerformanceGain = reward.PerformanceGain,
			ReputationGain = reward.ReputationGain,
		},
	})

	if not applyOk then
		-- The reward was resolved but could not be applied (e.g. the
		-- player's session ended between the checks above and here).
		-- Roll the instance back to pending so a legitimate retry (once
		-- the player has an active session again) is not blocked by a
		-- false "already completed".
		instances[instanceId] = instance
		return false, "failed to apply reward: " .. tostring(recordOrErr)
	end

	self:_pruneInstances(userId)

	local result = {
		ChoiceId = reward.ChoiceId,
		ResultLabel = reward.ResultLabel,
		QualityScore = reward.QualityScore,
		MoneyGain = reward.MoneyGain,
		PerformanceGain = reward.PerformanceGain,
		ReputationGain = reward.ReputationGain,
		NewPersonalMoney = recordOrErr.PersonalMoney,
		NewPerformanceRating = recordOrErr.PerformanceRating,
		NewReputation = recordOrErr.Reputation,
	}

	-- Promotion is checked here, server-side, as a direct side effect of
	-- completion - never in response to any client request (technical
	-- architecture §11; see this module's SECURITY MODEL comment and
	-- PromotionService.lua). `Money` is never read by this check at all.
	local promotionOk, promotionResult = self._promotionService:CheckAndPromote(userId)
	if promotionOk then
		result.Promotion = promotionResult
	end

	-- Always attach current progression status (Phase 3 "clear player-
	-- facing explanation" requirement: rank, thresholds, eligibility) -
	-- reflects the POST-promotion state when one just happened above.
	local statusOk, status = self._promotionService:GetStatus(userId)
	if statusOk then
		result.Rank = status.Rank
		result.PerformanceThreshold = status.PerformanceThreshold
		result.ReputationThreshold = status.ReputationThreshold
		result.PromotionEligible = status.EligibleForPromotion
	end

	return true, result
end

-- Test/diagnostic helper: returns how many instances (pending + completed)
-- are currently tracked for userId.
function TaskService:_instanceCount(userId)
	local instances = self._instances[userId]
	if not instances then
		return 0
	end
	local count = 0
	for _ in pairs(instances) do
		count = count + 1
	end
	return count
end

return TaskService
